# Generated by Django 4.2.3 on 2023-07-23 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("badminton", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="match",
        ),
        migrations.AddField(
            model_name="match",
            name="photo",
            field=models.ImageField(default="", upload_to="badminton/match/%Y/%m/%d"),
            preserve_default=False,
        ),
    ]
