# Generated by Django 4.2.3 on 2023-07-23 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("badminton", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="match",
        ),
    ]
