# Generated by Django 4.2.3 on 2023-07-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True, choices=[("M", "남성"), ("F", "여성")], max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="rating",
            field=models.IntegerField(
                choices=[
                    (2800, "선수 출신"),
                    (2700, "A조"),
                    (2600, "B조"),
                    (2500, "C조"),
                    (2000, "D조"),
                    (1500, "기본적인 스트로크 구사 가능자"),
                    (1000, "초보자"),
                ],
                default=1500,
            ),
        ),
    ]
